name: Hello World Workflow

on:
  push:
    branches:
      - main  # ou 'master' selon ta branche principale

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Affiche "Hello World"
        run: echo "👋 Hello, World! from GitHub Actions 🚀"
